variables:
  APP_ID: de.bschu.cashbox
  MANIFEST_PATH: $CI_PROJECT_DIR/${APP_ID}.yml
  BUNDLE: "${APP_ID}.flatpak"
  DOCKER_IMAGE: "ghcr.io/flathub-infra/flatpak-github-actions:gnome-47"
  SCHEDULE_TASK: default

stages:
  - setup
  - build-aarch64

.setup:
  stage: setup
  image: ${DOCKER_IMAGE}
  variables:
    RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
  before_script:
    # Add the flathub repository for installing build dependencies
    - flatpak remote-add --user --if-not-exists flathub ${RUNTIME_REPO}
    - gpg --list-keys --with-keygrip
    - echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
    - gpg-connect-agent reloadagent /bye
    - cat $GPG_PASSPHRASE | /usr/libexec/gpg-preset-passphrase --preset $GPG_KEY_GREP
    - gpg --import --batch ${GPG_PRIVATE_KEY}

build-aarch64:
  variables:
    ARCH: aarch64
  extends: .setup
  script:
    - flatpak-builder build --arch=${ARCH} --user --install-deps-from=flathub --gpg-sign=${GPG_KEY_ID} --disable-rofiles-fuse --disable-updates --force-clean --repo=repo ${BRANCH:+--default-branch=$BRANCH} ${MANIFEST_PATH}
    - echo flatpak build-bundle --gpg-sign=${GPG_KEY_ID} --arch=${ARCH} repo cashbox.${ARCH}.flatpak ${APP_ID}
    - flatpak build-bundle --gpg-sign=${GPG_KEY_ID} --arch=${ARCH} repo cashbox.${ARCH}.flatpak ${APP_ID}
  stage: build-aarch64
  artifacts:
    paths:
      - cashbox.${ARCH}.flatpak
  environment: production
  tags:
    - arm64
